name: CI Pipeline - Prod

on:
  push:
    paths:
      - '02-ci-build-and-test/**'
    branches:
      - main
      - dev

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 02-ci-build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t cicd-prod .

      - name: Run Container
        run: docker run -d -p 5000:5000 --name prod-container cicd-prod

      - name: Wait for App
        run: sleep 5

      - name: Fake Test
        run: echo "All tests passed successfully"