name: Deploy Pipeline

on:
  push:
    paths:
      - '04-deployment-success-but-app-down/**'
      - '.github/workflows/**'
    branches:
      - main
      - dev

jobs:
  build-test:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: 04-deployment-success-but-app-down
    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t cicd-prod .


      - name: Run Container
        run: docker run -d -p 5000:5000 -e API_KEY=$API_KEY --name prod-container cicd-prod

      - name: show logs
        run: docker logs prod-container

      - name: Wait for App
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000; then
              echo "App is up!"
              exit 0
            fi
            echo "Waiting for app..."
            sleep 2
          done

          echo "App failed to start"
          exit 1

      - name: Real Health Check
        run: curl -f http://localhost:5000

      - name: Cleanup container
        if: always()
        run: docker stop prod-container && docker rm prod-container